[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
rosc = "0.10.1"
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = "*"
serde = { version = "1.0.210", features= ["derive"] }
serde_json = "1.0"
rand = "0.8.5"

